import type {Step} from './types';
export const steps: Step[] = [
  {id:'restore',title:'恢复原任务',module:'LangGraphAgentExecutor.resume',inputLabel:'任务编号 + 修改意见',outputLabel:'原任务检查点',symbols:['LangGraphAgentExecutor.resume','LangGraphAgentExecutor._config'],highlights:{'LangGraphAgentExecutor.resume':[[71,85]],'LangGraphAgentExecutor._config':[[122,122]]},fields:['run_id','run_directory','layout','main_visual_path'],
    what:'第一次执行停在等待人工意见的位置。采集程序关闭执行器，再用同一个 SQLite 文件创建新执行器，读到了完全相同的状态。随后 resume 使用同一个任务编号继续图。这里没有重新生成初版海报。',
    why:'意见必须落到原来的海报上。任务编号被用作 thread_id，目录与中断检查限制了可以恢复的状态。本次重新打开执行器后，恢复前后的状态相等，是持久化恢复的直接证据；动画中的调用过程根据源码连接，并非逐行调试轨迹。',
    cost:'需要保留检查点和对应产物，并维护它们的对应关系。极简单的单次请求可以在内存里完成，但进程重启后就无法靠内存恢复。',without:'基于源码的推断：没有持久化状态，新执行器无法知道之前的布局和工具历史。本案例没有执行“删除数据库”的对照，因此不把它说成已观察到的故障。',pseudo:'状态 = 读取检查点(任务编号)\n确认状态属于这个任务，而且正在等待意见\n继续原来的图(修改意见)'},
  {id:'feedback',title:'接收意见，准备本轮',module:'human_review',inputLabel:'HumanDecision',outputLabel:'本轮状态',symbols:['human_review'],highlights:{human_review:[[15,17],[36,54]]},fields:['human_instruction','human_decision','round_number','tool_calls_in_round','round_base_layout','round_base_treatment','design_controls','analysis_before_round'],
    what:'人工意见成为 human_instruction，轮次变为 1，同时保存本轮开始的布局和背景处理参数。工具计数和轨迹被重置；本案例原来就是空轨迹，所以它们没有数值变化。',
    why:'这一轮需要有自己的起点，后面的工具与渲染才能对照修改前的状态。自然语言意见不等于结构化锁：本次 controls 为空，不能声称“背景不变”是由一个用户锁强制保证的。',
    cost:'保存布局副本会增加状态体积。这里是轮次快照，不是每行代码都记录一个快照。',without:'基于源码的推断：没有独立的本轮起点，后续约束检查和回退会失去原始参照。本次没有移除快照做实验。',pseudo:'本轮.意见 = 用户意见\n本轮.编号 = 已完成轮数 + 1\n本轮.起始布局 = 复制(当前布局)\n本轮.工具计数 = 0'},
  {id:'choose-tool',title:'选择一个工具',module:'react_decide',inputLabel:'意见 + 布局 + 已有报告',outputLabel:'modify_typography 决策',symbols:['react_decide','DesignAndReactProvider'],highlights:{react_decide:[[19,23],[30,45]],DesignAndReactProvider:[[41,69]]},fields:['react_decision'],
    what:'当前意见、布局和近期工具记录传给 JSON 提供者。此次提供者是已有测试替身，它返回 modify_typography，要求把 title 的字号设为 106。这里只是决定做什么，布局还没有改变。',
    why:'把决策与执行分开，才能先得到结构化动作，再交给受约束的工具处理。源码还限制每轮最多 3 次工具调用；这次只调用 1 次，没有触发预算上限。',
    cost:'结构化动作限制了表达范围，也需要维护校验和工具列表。测试替身证明链路可以工作，不能证明真实模型会作出同样决策。',without:'基于源码的推断：移除预算后，这一处不再强制结束工具循环，但图或调用方可能还有其他限制。本次没有测试无限循环，也没有实际触发三次上限。',pseudo:'如果 本轮工具次数 >= 3：结束本轮\n否则：决策 = 提供者(意见, 布局, 工具记录)\n校验决策格式\n保存决策'},
  {id:'execute-tool',title:'校验工具，修改布局',module:'execute_react_tool',inputLabel:'工具参数 + 当前布局',outputLabel:'新布局 + Observation',symbols:['execute_react_tool','ReactToolRegistry.execute','apply_optimization_actions','_validate_action','_require_number','LayoutElement'],highlights:{execute_react_tool:[[21,45],[48,54]],'ReactToolRegistry.execute':[[103,110],[122,128]],apply_optimization_actions:[[23,23],[32,36],[51,52],[61,61]],_validate_action:[[24,29]],_require_number:[[66,71]],LayoutElement:[[40,40]]},fields:['layout','tool_calls_in_round','tool_traces','background_treatment'],
    what:'工具接受 title 的字号动作，复制布局后写入 106，返回成功 Observation。工具计数从 0 变为 1。此时改变的是排版数据，磁盘里的修改版海报还没有生成。',
    why:'提供者给出的参数仍需校验。工具注册表限定动作与目标，动作校验检查字号范围，最后数据模型再次校验整个布局。本次成功轨迹证明执行完成；每个内部校验的独立返回值未采集。',
    cost:'多层校验有重复规则，维护时需要保持一致。下方对照只移除第一层字号校验：999 仍被最终的数据模型拒绝，两次都未修改调用方布局。',without:'已执行隔离对照：相同布局和字号 999，原函数抛出 ActionValidationError；仅去掉首个 validate_actions 调用的副本抛出 ValidationError。并没有产生非法海报。',pseudo:'校验(动作, 当前布局)\n新布局 = 深复制(当前布局)\n新布局.title.字号 = 106\n再次校验(新布局)\n返回 新布局和执行说明'},
  {id:'finish-loop',title:'结束工具循环',module:'react_decide',inputLabel:'新布局 + 工具 Observation',outputLabel:'finish_round 决策',symbols:['react_decide','DesignAndReactProvider'],highlights:{react_decide:[[30,45]],DesignAndReactProvider:[[41,69]]},fields:['react_decision','tool_calls_in_round','tool_traces'],
    what:'测试替身第二次收到布局和成功 Observation，返回 finish_round。它是图的流转决定，不是又执行了一次工具。工具计数仍然是 1。',
    why:'一次修改可以包含多次数据操作，而统一渲染放在循环结束后。此处记录保留了提供者收到的完整消息，能检查它看到的是更新后的布局。',
    cost:'循环结束前，现有分析仍对应上一张已经渲染的海报，而非刚改过的布局；不能把旧测量当成新效果。',without:'基于源码的推断：若每个工具后都重新渲染，会增加中间产物和计算开销。本章没有采集这种替代实现的耗时。',pseudo:'决策 = 提供者(更新后布局, 执行说明)\n如果 决策是结束：转到渲染\n否则：继续下一个工具'},
  {id:'render',title:'生成修改后的海报',module:'render_round',inputLabel:'新布局 + 主视觉路径',outputLabel:'图片文件 + 实际文字信息',symbols:['render_round'],highlights:{render_round:[[24,37],[47,52]]},fields:['poster_optimized_path','rendered_text_facts','layout','background_treatment','main_visual_path','round_rejection_reason'],
    what:'真实 Pillow 渲染器读取原主视觉文件，把新布局绘制成 poster_round_1.png。实际绘制的标题字号从 88 变成 106。本次未触发渲染后的回退。路径是文件引用，不是图片内容在对象里传递。',
    why:'主视觉和文字排版分开后，这次改字只需要重新排版。采集到的主视觉字节哈希前后一致、背景处理参数相等，而且图片提供者调用次数仍为 1，三种证据共同支持本次复用背景。',
    cost:'布局参数不总等于最终画出来的结果，字体适配可能缩小字号，所以同时保留实际文字信息。这里只证明测试背景被复用，不证明真实生成模型的美术质量。',without:'基于源码的推断：若把文字烘焙进唯一一张生成图，当前布局工具无法直接改动图中的文字，需要重绘、图像编辑或其他方案。本次未实现并比较那些替代方案。',pseudo:'读取图片(主视觉路径)\n按照新布局绘制文字\n保存修改版图片\n返回 图片路径和实际字号'},
  {id:'evaluate',title:'复评实际结果',module:'evaluate_optimized',inputLabel:'修改版路径 + 布局',outputLabel:'报告 + 设计分析',symbols:['evaluate_optimized'],highlights:{evaluate_optimized:[[78,87]]},fields:['evaluation_optimized','analysis_current','goal_verification'],
    what:'图片写出后，复评节点生成报告和设计分析。本次标题实际变大了，但 goal_verification.outcome 仍是 not_met：活动信息的可读性检查未通过。总分虽然是 100，实际可用权重只有 40/100，视觉模型和注意力信号均不可用。不能把这个数字当成完整质量满分。',
    why:'工具成功只说明动作执行完成，并不等于达到设计目标。报告把版面检查、可用信号和测量结果留给后续比较与人工判断。',
    cost:'本次未连接视觉模型和 DeepGaze。报告覆盖的只是本地可获得的部分信号，并非完整审美评价。',without:'基于源码的推断：没有复评，后续 complete_round 缺少所需的新报告，会在前置检查处拒绝继续。本次没有移除复评节点做反例。',pseudo:'报告 = 检查(已渲染海报, 布局)\n分析 = 读取实际文字和背景特征\n保存报告与分析'},
  {id:'save-round',title:'保存本轮快照',module:'complete_round',inputLabel:'图片路径 + 报告 + 工具轨迹',outputLabel:'RoundSnapshot',symbols:['complete_round'],highlights:{complete_round:[[63,89]]},fields:['round_snapshots','iteration'],
    what:'节点把本轮图片名、报告、工具轨迹和控制参数组合成一个 RoundSnapshot，加入状态中的轮次列表。checkpoint 随后持久化这份状态，本次轮次列表从 0 项变为 1 项。',
    why:'把结果和产生它的动作一起保存，才能回答这一版怎么来的。源码会先检查报告是否可比，不能只看到分数数字就直接相减并宣称变好。',
    cost:'快照会增长，也依赖相应图片仍然存在。它记录节点产出，不包含每行 Python 的中间变量。',without:'基于源码的推断：缺少轮次快照，后续人工检查点无法按现有方式展示轮次历史。没有删除快照做运行实验。',pseudo:'比较 = 比较同条件报告(上轮, 本轮)\n快照 = 图片名 + 报告 + 工具轨迹\n轮次列表.追加(快照)'},
  {id:'review',title:'准备候选，再次等待',module:'propose_layout_candidates → human_review',inputLabel:'当前结果 + 本轮快照',outputLabel:'候选 + 人工检查点',symbols:['propose_layout_candidates','build_human_checkpoint','human_review'],highlights:{propose_layout_candidates:[[59,69],[90,115]],build_human_checkpoint:[[97,136]],human_review:[[15,17]]},fields:['layout_candidates','round_snapshots'],
    what:'当前源码还会生成并比较排版候选，然后再次在 human_review 中断。最终返回 waiting_for_human，修改后的正式海报保留为本轮产物；候选没有被自动选中。本章到这里结束。',
    why:'让用户继续判断需要什么，而不是把一次工具成功等同于最终交付。检查点包含轮次结果和可选布局，下一次意见仍可恢复同一个任务。',
    cost:'候选还会产生额外渲染。本章保存了候选元数据和渲染调用记录，但没有打包候选图片；相应图片预览明确为未采集。前端 SSE 通知也未采集。',without:'基于源码的推断：若自动选择候选，会改变本次“等待用户确认”的行为。这不是本章已经执行的分支，因此不制作虚假的自动选中结果。',pseudo:'候选 = 比较当前布局与备选布局\n检查点 = 当前结果 + 轮次历史 + 候选\n暂停图，等待下一次用户意见'},
];
