import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync,existsSync} from 'node:fs';
mkdirSync('.runtime',{recursive:true});
const localChrome='C:/Program Files/Google/Chrome/Application/chrome.exe';
const executablePath=process.env.CHROME_PATH || (existsSync(localChrome)?localChrome:undefined);
const browser=await chromium.launch({executablePath,headless:true});
const context=await browser.newContext({viewport:{width:1600,height:1100},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();
const errors=[],requests=[],passed=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({method:r.method(),url:r.url(),type:r.resourceType()}));
const app=page.getByTestId('app');
const frame=async()=>Number(await app.getAttribute('data-frame'));
const stop=i=>30+i*120+119;
async function settled(f){await page.waitForFunction(f=>{const a=document.querySelector('[data-testid=app]');return a?.getAttribute('data-frame')===String(f)&&a?.getAttribute('data-playing')==='false';},f,{timeout:12000});}
async function check(name,fn){await fn();passed.push(name);console.log('PASS',name);}
async function jump(i){await page.getByTestId(`step-${i}`).click();await settled(stop(i));}
async function scrub(f){await page.getByRole('slider',{name:'教学进度',exact:true}).fill(String(f));await settled(f);}
try{
 await page.goto('http://127.0.0.1:8891/');await app.waitFor();
 await check('initial paused and actual initial poster visible',async()=>{await settled(0);assert.equal(await page.locator('.stage img').getAttribute('src'),'/case/poster_initial.png');});
 await page.screenshot({path:'.runtime/initial.png',fullPage:true});
 await check('first next plays first business step and stops exactly',async()=>{await page.getByRole('button',{name:'下一步',exact:true}).click();await settled(stop(0));});
 await check('continue from stop does not stop at same frame',async()=>{await page.getByRole('button',{name:'播放',exact:true}).click();await settled(stop(1));});
 await check('4x next and replay cannot miss teaching stop',async()=>{await page.getByRole('combobox',{name:'播放倍速'}).selectOption('4');await page.getByRole('button',{name:'下一步',exact:true}).click();await settled(stop(2));await page.getByRole('button',{name:'↺ 重播本步',exact:true}).click();await settled(stop(2));});
 await check('previous and directory jump stay paused',async()=>{await page.getByRole('button',{name:'上一步',exact:true}).click();await settled(stop(1));await jump(5);assert.equal(await page.getByTestId('inspector').getAttribute('data-step'),'render');assert.equal(await page.locator('.stage img').getAttribute('src'),'/case/poster_round_1.png');});
 await check('scrub syncs source, data, explanation and poster without future output',async()=>{await scrub(400);assert.equal(await app.getAttribute('data-step'),'execute-tool');assert.equal(await page.getByTestId('inspector').getAttribute('data-step'),'execute-tool');assert.equal(await page.getByTestId('explanation').getAttribute('data-step'),'execute-tool');assert.equal(await page.locator('.stage img').getAttribute('src'),'/case/poster_initial.png');await page.getByRole('tab',{name:'输出',exact:true}).click();assert.match(await page.getByTestId('inspector').innerText(),/尚未执行到返回/);});
 await check('replay resets current step and does not carry future poster',async()=>{await jump(3);await page.getByRole('combobox',{name:'播放倍速'}).selectOption('0.5');await page.getByRole('button',{name:'↺ 重播本步',exact:true}).click();await page.waitForTimeout(100);assert.ok((await frame())<468);assert.equal(await page.locator('.stage img').getAttribute('src'),'/case/poster_initial.png');await page.getByRole('button',{name:'暂停',exact:true}).click();});
 await check('paused JSON expands and copies without playback',async()=>{await jump(3);await page.getByRole('tab',{name:'输出',exact:true}).click();await page.getByRole('button',{name:'复制 JSON',exact:true}).click();const text=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(JSON.parse(text).layout.elements[0].font_size,106);await page.getByText('展开为完整 JSON 文本',{exact:true}).click();await settled(stop(3));});
 await check('source copies and text selection ignores keyboard shortcuts',async()=>{await page.getByRole('tab',{name:'源码',exact:true}).click();await page.getByRole('button',{name:'复制源码',exact:true}).click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/async def execute_react_tool/);await page.locator('.source-code').evaluate(el=>{const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);});await page.keyboard.press('Space');await settled(stop(3));await page.evaluate(()=>window.getSelection().removeAllRanges());await page.getByRole('combobox',{name:'播放倍速'}).focus();await page.keyboard.press('ArrowRight');await settled(stop(3));});
 await check('data object click selects captured data without resuming',async()=>{await page.locator('.stage button').filter({hasText:'工具参数 + 当前布局'}).click();assert.equal(await page.getByRole('tab',{name:'输入',exact:true}).getAttribute('aria-selected'),'true');await settled(stop(3));});
 await check('counterfactual is separate and restores exact paused main position',async()=>{await scrub(470);await page.getByRole('button',{name:'没有这项设计会怎样 ↗',exact:true}).click();await page.getByTestId('comparison').waitFor();assert.match(await page.getByTestId('comparison').innerText(),/ActionValidationError/);assert.match(await page.getByTestId('comparison').innerText(),/ValidationError/);await page.getByRole('button',{name:'返回原学习位置',exact:true}).click();await settled(470);assert.equal(await page.getByTestId('inspector').getAttribute('data-step'),'execute-tool');});
 await check('continuous mode passes stops, manual pause and next still works',async()=>{await jump(0);await page.getByRole('button',{name:'连续模式',exact:true}).click();await page.getByRole('combobox',{name:'播放倍速'}).selectOption('4');await page.getByRole('button',{name:'播放',exact:true}).click();await page.waitForFunction(()=>Number(document.querySelector('[data-testid=app]')?.getAttribute('data-frame'))>285);assert.equal(await app.getAttribute('data-playing'),'true');await page.getByRole('button',{name:'暂停',exact:true}).click();const i=Math.floor(((await frame())-30)/120);await page.getByRole('button',{name:'下一步',exact:true}).click();await settled(stop(Math.min(8,i+1)));});
 await check('rapid navigation has one final target',async()=>{await scrub(0);await page.getByRole('button',{name:'学习模式',exact:true}).click();await page.getByRole('button',{name:'下一步',exact:true}).evaluate(el=>{el.click();el.click();el.click();});await settled(stop(2));});
 await check('4x learning mode stops at each remaining boundary',async()=>{for(let i=3;i<9;i++){await page.getByRole('button',{name:'播放',exact:true}).click();await settled(stop(i));}});
 await check('all nine directory entries reflect same panels and stay paused',async()=>{const ids=['restore','feedback','choose-tool','execute-tool','finish-loop','render','evaluate','save-round','review'];for(let i=0;i<9;i++){await jump(i);assert.equal(await page.getByTestId('inspector').getAttribute('data-step'),ids[i]);assert.equal(await page.getByTestId('explanation').getAttribute('data-step'),ids[i]);}});
 await jump(3);await page.getByRole('tab',{name:'状态变化',exact:true}).click();await page.screenshot({path:'.runtime/step-tool.png',fullPage:true});
 await page.getByRole('button',{name:'没有这项设计会怎样 ↗',exact:true}).click();await page.screenshot({path:'.runtime/comparison.png',fullPage:true});await page.getByRole('button',{name:'返回原学习位置',exact:true}).click();
 await check('layout collapses and resizes without playback',async()=>{await page.getByRole('button',{name:'收起目录',exact:true}).click();await page.getByRole('slider',{name:'检查面板宽度',exact:true}).fill('510');await settled(stop(3));});
 await check('keyboard on ordinary page advances a business step',async()=>{await page.locator('h1').click();await page.keyboard.press('ArrowLeft');await settled(stop(2));await page.keyboard.press('ArrowRight');await settled(stop(3));});
 await check('pointer scrubbing pauses and synchronizes the visible step',async()=>{const range=page.getByRole('slider',{name:'教学进度',exact:true});await range.scrollIntoViewIfNeeded();const b=await range.boundingBox();await page.mouse.move(b.x+b.width*.45,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width*.2,b.y+b.height/2,{steps:8});await page.mouse.up();await page.waitForTimeout(100);assert.equal(await app.getAttribute('data-playing'),'false');assert.equal(await app.getAttribute('data-step'),await page.getByTestId('inspector').getAttribute('data-step'));assert.ok((await frame())>180&&(await frame())<260);});
 await check('desktop sizes have no horizontal page overflow',async()=>{await page.getByRole('button',{name:'展开目录',exact:true}).click();await page.getByRole('slider',{name:'检查面板宽度',exact:true}).fill('420');for(const size of [{width:1920,height:1080},{width:1366,height:900}]){await page.setViewportSize(size);await page.evaluate(()=>window.scrollTo(0,0));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:`.runtime/desktop-${size.width}.png`,fullPage:true});}});
 await check('entire replay makes only static GET requests and has no browser errors',async()=>{assert.deepEqual(errors,[]);assert.ok(requests.every(r=>r.method==='GET'&&r.url.startsWith('http://127.0.0.1:8891/')&&!r.url.includes('/api/')));assert.equal(requests.filter(r=>r.type==='fetch').length,1);});
 writeFileSync('.runtime/browser-results.json',JSON.stringify({testedAt:new Date().toISOString(),passed,requests,errors},null,2));
 console.log(`Completed ${passed.length} browser checks.`);
}catch(error){await page.screenshot({path:'.runtime/failure.png',fullPage:true});console.error(error);process.exitCode=1;}
finally{await browser.close();}
