import { createWorkbench } from "./workbench.js";
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = v => esc(JSON.stringify(v, null, 2) ?? '尚未产生');
let saved = {};
try { saved = JSON.parse(localStorage.getItem('posterpilot-learning-v1') || '{}'); } catch {}
const state = {mode:'learn', node:'system', expanded:new Set(['system','production']), done:new Set(saved.done || []), search:'', line:1, source:false, path:null, quiz:{}, lab:'filter', result:null, previous:null, labIndex:0, trace:null, index:0, scenario:'normal', title:'春日摄影展', speed:1100, playing:false, field:'status', values:{}, error:'', busy:false};
let data, nodes, timer, requestId = 0;
const sourceCache = new Map();
const kinds = {repository:'仓库原函数 · 真实执行',teaching:'教学代码 · 本地执行',planned:'规划方案 · 本地模拟'};
async function api(url, options) { const r = await fetch(url, options); const value = await r.json(); if(!r.ok) throw new Error(value.error || '本地服务暂时不可用'); return value; }
const children = id => data.nodes.filter(n=>n.parent===id);
const workbench=createWorkbench({state,esc,json,children,ancestors,codePanel,transport,sourceCache,kinds,data:()=>data,nodes:()=>nodes});
function ancestors(id) { const out=[]; let n=nodes.get(id); while(n) {out.unshift(n); n=nodes.get(n.parent);} return out; }
function persist(){try{localStorage.setItem('posterpilot-learning-v1',JSON.stringify({done:[...state.done]}));}catch{toast('浏览器未允许保存，当前学习仍可继续');}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),2200);}
function stop(){clearTimeout(timer);state.playing=false;}
function navigate(id){if(!nodes.has(id))return;stop();state.node=id;state.mode='learn';state.line=1;state.source=false;state.error='';ancestors(id).forEach(n=>state.expanded.add(n.id));location.hash=id;render();window.scrollTo(0,0);}
function tree(id,depth=0){const n=nodes.get(id), kids=children(id), query=state.search.toLowerCase();const matches=!query || [n,...descendants(id)].some(x=>(x.title+' '+x.summary+' '+x.id).toLowerCase().includes(query));if(!matches)return '';const open=query||state.expanded.has(id);return `<div class="tree-row ${state.node===id?'selected':''} ${state.done.has(id)?'done':''}" style="padding-left:${depth*10}px">${kids.length?`<button class="toggle" data-action="toggle" data-id="${id}" aria-label="${open?'收起':'展开'} ${esc(n.title)}" aria-expanded="${!!open}">${open?'−':'+'}</button>`:`<span class="leaf-mark">${state.done.has(id)?'✓':'·'}</span>`}<button class="nav-node" data-action="node" data-id="${id}" ${state.node===id?'aria-current="page"':''}>${esc(n.title)}</button>${n.status==='planned'?'<span class="planned-dot" title="规划中"></span>':''}</div>${kids.length&&open?kids.map(k=>tree(k.id,depth+1)).join(''):''}`;}
function descendants(id){return children(id).flatMap(n=>[n,...descendants(n.id)]);}
function sidebar(){return `<aside class="sidebar"><div class="brand"><span class="brand-mark">P/</span><div><div class="brand-name">PosterPilot 学习台</div><small>从业务，走进每一行代码</small></div></div><div class="side-search"><label class="sr-only" for="search">搜索模块</label><input id="search" placeholder="搜索模块、功能或关键词" value="${esc(state.search)}"></div><nav class="sidebar-nav" aria-label="项目模块"><div class="nav-label">项目地图 / PROJECT MAP</div>${tree('system')}</nav><div class="side-footer"><p><span>我已理解</span><span>${state.done.size} / ${data.nodes.length}</span></p><div class="progress-track"><span style="width:${state.done.size/data.nodes.length*100}%"></span></div><span class="offline-dot"></span>本地学习 · 无模型调用费用</div></aside>`;}
function render(){const openDetails=[...document.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent);const running=state.mode==='runtime'?state.trace?.steps[state.index]?.node:state.mode==='lab'?state.result?.node:null;if(running)ancestors(running).forEach(n=>state.expanded.add(n.id));const focused=document.activeElement;const focusKey=focused?.dataset?.action?{...focused.dataset}:null;const sidebarScroll=$('.sidebar-nav')?.scrollTop||0;$('#app').innerHTML=`<div class="shell">${sidebar()}<div class="workspace"><header class="topbar"><button class="mobile-toggle" data-action="menu" aria-label="打开模块菜单">目录</button><nav class="main-tabs" aria-label="学习方式">${[['learn','逐层拆解'],['runtime','运行回放'],['lab','动手实验'],['glossary','术语词典']].map(([key,label])=>`<button data-action="mode" data-id="${key}" class="${state.mode===key?'active':''}">${label}</button>`).join('')}</nav><a class="topbar-name" href="/flow-overview.html" target="_blank" rel="noopener">完整流程图 ↗</a></header><main id="main" class="main" tabindex="-1">${state.error?`<div role="alert" class="error">${esc(state.error)}</div>`:''}${state.mode==='learn'?lesson():state.mode==='runtime'?runtime():state.mode==='lab'?lab():glossary()}</main></div></div>`;$('.sidebar-nav').scrollTop=sidebarScroll;document.querySelectorAll('details').forEach(d=>{if(openDetails.includes(d.querySelector('summary')?.textContent))d.open=true;});if(focusKey){const match=[...document.querySelectorAll('[data-action]')].find(el=>Object.entries(focusKey).every(([k,v])=>el.dataset[k]===v));match?.focus({preventScroll:true});}const runningRow=running?document.querySelector('.nav-node[data-id='+running+']')?.parentElement:null;runningRow?.classList.add('running');}
function crumbs(id){return `<nav class="breadcrumbs" aria-label="当前位置">${ancestors(id).map(n=>`<button data-action="node" data-id="${n.id}">${esc(n.title)}</button>`).join('<span>›</span>')}</nav>`;}
function codePanel(lines,selected,{start=1,clickable=false,title='初级伪代码',meta='',note='',stack=[],stackLabel='调用栈'}={}){return `<section class="code-panel runtime-code"><div class="panel-heading">${esc(title)}</div>${meta?`<div class="code-meta">${esc(meta)}</div>`:''}${stack.length?`<div class="stack"><span>${esc(stackLabel)}</span>${stack.map(x=>`<span>${esc(x)}</span>`).join(' → ')}</div>`:''}<div class="code-lines">${lines.map((line,i)=>`<div class="code-line ${selected===i+start?'selected':''} ${clickable?'clickable':''}" ${clickable?`role="button" tabindex="0" data-action="line" data-id="${i+start}"`:''} data-line="${i+start}"><span class="ln">${i+start}</span><code>${esc(typeof line==='string'?line:line.text) || ' '}</code></div>`).join('')}</div>${note?`<div class="line-explanation">${esc(note)}</div>`:''}</section>`;}
function lesson(){return workbench.lesson();}
function transport(kind,total,index){return `<div class="transport" aria-label="播放控制"><button data-action="reset" data-kind="${kind}">重置</button><button data-action="prev" data-kind="${kind}" ${index===0?'disabled':''}>上一步</button><button class="primary" data-action="play" data-kind="${kind}" ${index===total-1?'disabled':''}>${state.playing?'暂停':'播放'}</button><button data-action="next" data-kind="${kind}" ${index===total-1?'disabled':''}>下一步</button><span class="step-count">${index+1} / ${total}</span><input type="range" aria-label="运行步骤" min="0" max="${total-1}" value="${index}" data-kind="${kind}" id="seek"><select id="speed" aria-label="播放速度">${[[1800,'慢速'],[1100,'正常'],[500,'快速']].map(([v,t])=>`<option value="${v}" ${state.speed===v?'selected':''}>${t}</option>`).join('')}</select></div>`;}
function runtime(){return workbench.runtime();}
function lab(){return workbench.lab();}
function glossary(){return `<div class="trace-header"><div class="eyebrow">术语用人话说</div><h1>读懂代码前，先读懂这些词</h1><p>每个词都可以回到它在项目中出现的位置。</p></div><div class="glossary-grid">${Object.entries(data.glossary).map(([term,definition])=>`<section class="glossary-item"><h2>${esc(term)}</h2><p>${esc(definition)}</p><div class="small-actions">${data.nodes.filter(n=>n.terms.includes(term)).map(n=>`<button data-action="node" data-id="${n.id}">${esc(n.title)} ↗</button>`).join('')}</div></section>`).join('')}</div>`;}
async function loadTrace(){const id=++requestId;stop();state.busy=true;state.error='';render();try{const result=await api('/api/trace?'+new URLSearchParams({scenario:state.scenario,title:state.title}));if(id!==requestId)return;state.trace=result;state.index=0;}catch(e){state.error=e.message;}finally{if(id===requestId){state.busy=false;render();}}}
function syncView(){render();for(const selector of ['.runtime-step.current','.runtime-code .code-line.selected']){const item=$(selector);if(item){const pane=item.parentElement;const a=item.getBoundingClientRect(),b=pane.getBoundingClientRect();pane.scrollTop+=a.top-b.top-pane.clientHeight/2+item.clientHeight/2;if(pane.scrollWidth>pane.clientWidth&&selector.includes('runtime-step'))pane.scrollLeft+=a.left-b.left;}}}
function stepTo(kind,index){stop();if(kind==='lab')state.labIndex=Math.max(0,Math.min(state.result.steps.length-1,index));else state.index=Math.max(0,Math.min(state.trace.steps.length-1,index));syncView();}
function play(kind){if(state.playing){stop();render();return;}state.playing=true;render();const tick=()=>{if(!state.playing)return;const arr=kind==='lab'?state.result.steps:state.trace.steps;let i=kind==='lab'?state.labIndex:state.index;if(i>=arr.length-1){stop();render();return;}i++;if(kind==='lab')state.labIndex=i;else state.index=i;if(i===arr.length-1||arr[i].wait)stop();syncView();if(state.playing)timer=setTimeout(tick,state.speed);};timer=setTimeout(tick,state.speed);}
async function action(el){const a=el.dataset.action,id=el.dataset.id,kind=el.dataset.kind;const index=kind==='lab'?state.labIndex:state.index;switch(a){case 'node':navigate(id);return;case 'toggle':state.expanded.has(id)?state.expanded.delete(id):state.expanded.add(id);break;case 'menu':$('.shell').classList.toggle('menu-open');return;case 'mode':stop();state.mode=id;state.error='';render();if(id==='runtime'&&!state.trace)await loadTrace();return;case 'line':state.line=Number(id);break;case 'pseudo':state.source=false;break;case 'source':state.source=true;render();try{if(!sourceCache.has(state.node)){const node=state.node;sourceCache.set(node,await api('/api/source?id='+encodeURIComponent(node)));}}catch(e){state.error=e.message;}break;case 'done':state.done.has(state.node)?state.done.delete(state.node):state.done.add(state.node);persist();break;case 'quiz':state.quiz[state.node]=Number(id);break;case 'path':state.path=id;navigate(data.paths.find(p=>p.id===id).nodes[0]);return;case 'path-exit':state.path=null;break;case 'path-next':case 'path-prev':{const p=data.paths.find(p=>p.id===state.path),i=p.nodes.indexOf(state.node);navigate(p.nodes[Math.max(0,i+(a==='path-next'?1:-1))]);return;}case 'term':$('#term-content').innerHTML=`<h2>${esc(id)}</h2><p>${esc(data.glossary[id]||'此术语暂未收录。')}</p>`;$('#term-dialog').showModal();return;case 'open-lab':stop();if(state.lab!==id){state.result=null;state.previous=null;state.labIndex=0;}state.lab=id;state.mode='lab';state.error='';break;case 'seek':stepTo(kind,Number(id));return;case 'reset':stepTo(kind,0);return;case 'prev':stepTo(kind,index-1);return;case 'next':stepTo(kind,index+1);return;case 'play':play(kind);return;case 'over':case 'out':{const steps=state.result.steps,current=steps[state.labIndex];let next=steps.findIndex((s,i)=>i>state.labIndex&&(a==='out'?s.event==='return'&&s.stack.length===current.stack.length:s.stack.length<=current.stack.length));stepTo('lab',next<0?steps.length-1:next);return;}}render();}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)action(el);});
document.addEventListener('keydown',e=>{if(e.target.closest('.code-line.clickable,.diagram-node')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();action(e.target.closest('[data-action]'));}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;$('.sidebar-nav').innerHTML=`<div class="nav-label">项目地图 / PROJECT MAP</div>${tree('system')||'<p class="empty">没有找到相关模块</p>'}`;}});
document.addEventListener('change',e=>{if(e.target.id==='learning-path'){if(e.target.value)action({dataset:{action:'path',id:e.target.value}});else {state.path=null;render();}}if(e.target.id==='lab-choice')action({dataset:{action:'open-lab',id:e.target.value}});if(e.target.id==='step-jump')stepTo('trace',Number(e.target.value));if(e.target.id==='lab-jump')stepTo('lab',Number(e.target.value));if(e.target.id==='seek')stepTo(e.target.dataset.kind,Number(e.target.value));if(e.target.id==='speed')state.speed=Number(e.target.value);if(e.target.id==='provenance'){state.field=e.target.value;render();}if(e.target.closest('#lab-form')){const l=data.labs.find(x=>x.id===state.lab);state.values[l.id]=readFields(l,e.target.closest('form'));}});
function readFields(l,form){return Object.fromEntries(l.fields.map(f=>{const el=form.elements.namedItem(f.key);return [f.key,f.type==='checkbox'?el.checked:f.type==='number'?Number(el.value):el.value];}));}
document.addEventListener('submit',async e=>{if(e.target.id==='trace-form'){e.preventDefault();const form=new FormData(e.target);state.scenario=form.get('scenario');state.title=form.get('title');await loadTrace();}if(e.target.id==='lab-form'){e.preventDefault();stop();const l=data.labs.find(x=>x.id===state.lab),values=readFields(l,e.target);state.values[l.id]=values;state.busy=true;state.error='';render();try{const r=await api('/api/lab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:l.id,values})});if(state.lab===l.id){state.previous=state.result;state.result=r;state.labIndex=0;}}catch(err){state.error=err.message;}finally{state.busy=false;render();}}});
window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(nodes?.has(id)&&state.node!==id)navigate(id);});
try {data=await api('/api/catalog');nodes=new Map(data.nodes.map(n=>[n.id,n]));state.done=new Set([...state.done].filter(id=>nodes.has(id)));const id=decodeURIComponent(location.hash.slice(1));if(nodes.has(id))state.node=id;ancestors(state.node).forEach(n=>state.expanded.add(n.id));render();}catch(e){$('#app').innerHTML=`<div class="boot error"><h1>学习台暂时无法连接</h1><p>${esc(e.message)}</p><p>请通过“开始学习.cmd”启动本地服务，然后刷新页面。</p></div>`;}
