// One visual workspace, with its explanation and code kept beside it.
const descriptions = {
  system:'PosterPilot 把一张海报的制作拆成几件相互配合的事：先收好活动需求，再生成背景、排好文字，最后检查并交给你确认。你不满意时可以提出具体修改，程序会保留任务记录，模型只能在允许的范围内使用工具。画布里是这些模块的组成关系，点进一个模块，就能继续看它里面的细节。',
  intake:'这一层先把表单里的标题、时间、地点和尺寸整理好，检查没问题后再创建任务，并给它一个独立编号。后面的生成步骤都靠这份信息继续工作，所以这里不能省掉；否则空标题或错误尺寸可能一直传到渲染时才出错。先检查再开始，也能让用户马上知道应该改哪里。',
  brief:'你填的内容要先经过检查，比如标题不能全是空格，当前模板也只接受竖版画布。检查通过后，后面的程序就能按同一套约定读取数据，不必各自猜测输入是什么。地点等可选信息没有填写就保持为空，不能让模型替你编出来。',
  production:'初版海报按固定顺序完成：找设计参考、确定方案、生成背景、叠加准确的文字，再检查结果。模型负责比较开放的设计建议，程序负责文字、尺寸和执行顺序。这样即使背景是模型生成的，活动事实和最终排版仍然有明确的控制方式。',
  rag:'这一步从知识库里找少量相关的设计建议，并把来源一起交给模型。它能帮助模型参考已有经验，但不是生成海报的唯一办法；没有合适知识时，仍可以依靠基础模板。关键是先筛掉不该使用的内容，再查相似度，不能因为某条知识看起来很像就直接采用。',
  query:'检索需要一个明确的问题，所以程序会把活动主题、风格和视觉元素整理成查询文字。例如只搜“摄影展”比较宽泛，加上“清新”“相机”等信息，就能更清楚地表达这次在找什么。这里只整理已有需求，不替用户添加新的活动事实。',
  filter:'先看一条知识有没有通过审核、适不适合当前用途和区域，再决定是否让它参加检索。相似度只能说明内容接近，不能代替这些业务判断。少了这一步，待审核的建议也可能被模型当作设计依据；画布里的筛选会把它们挡在前面。',
  'filter-status':'普通生成只使用审核通过的知识卡，待审核和已拒绝的内容默认不会进入候选。这样可以避免未经确认的建议直接影响海报。审核通过也不意味着永远正确，后续仍需要维护和复核；实验里的开关可以让你看到放开候选状态后结果怎样改变。',
  'filter-scope':'同一条知识可能只适合标题，也可能只适合评测，所以程序还会检查这次的用途和目标区域。范围为空表示没有这项限制，含义相同的区域名称会先统一处理。这样才不会把背景构图的建议误当成活动信息的排版规则。',
  recall:'程序把查询转换成向量，再从已经筛好的候选中查找语义相近的内容。这让用词不同但意思接近的知识也有机会被找到。向量服务不可用时，当前代码会返回空结果并说明原因，不会悄悄编造检索命中，也不会自动改用词法检索。',
  rank:'召回结果还要再排序。当前实现把语义分数乘以 0.85、字面相似度乘以 0.15，再合起来，最后按阈值和数量限制留下结果。字面分数起辅助作用，能提供另一种匹配线索，但分数高仍不能代替前面的审核和适用范围检查。',
  bigrams:'先把两段文字清理成统一格式，再各自拆成连续两个字的组合，比如“摄影展”会变成“摄影”和“影展”。共同的字对越多，算出来的字面相似度通常越高。这个计算不理解深层语义，所以项目把它作为向量分数的补充，而不是唯一依据。',
  citations:'检索返回知识内容时，也要把对应的卡片编号和来源带回去。以后看到某个设计建议，就能查清它参考了哪里，而不是只得到一句“模型认为这样更好”。没有命中就保留空引用，不能为了让结果显得有依据而补造来源。',
  planning:'模型根据需求和参考知识提出颜色、视觉描述等设计方案，程序再检查输出格式，并用模板生成可渲染的布局。活动文字继续来自用户输入。把模型建议和程序约束接起来，才能避免一份看起来不错的回答到了渲染时却无法使用。',
  image:'图片服务接收画面描述，返回背景图，程序把它保存下来供后面排版使用。这里尽量让模型生成没有文字的画面，准确的中文再由程序叠加。如果已经有授权背景，也可以复用它；学习台使用示例数据，不会在这里发起付费生成。',
  render:'程序把背景和文字布局合成一张海报，文字内容来自活动需求，字体和位置来自布局参数。这样日期、地点等信息可以准确绘制，也能单独修改。只依赖图片模型把全部文字画出来，容易出现错字，而且改一个日期可能需要重做整张图。',
  fonts:'先选择用户指定的字体，或者根据案例和活动类型选择默认字体，再检查字体文件和字符是否齐全。当前实现遇到缺字时可能把整个标题回退到常规粗体，这也是艺术效果变弱的原因之一。独立生成手绘标题层是后续方案，现有代码仍以字体排版为主。',
  fit:'同样大小的文字，不一定能放进同一个框。程序会先测量和换行，如果高度仍然超出，就在允许范围内缩小字号，再试一次。最后保存实际使用的尺寸，后面的检查才能看到真正画出来的文字，而不是只看到最初请求的字号。',
  evaluate:'生成成功只说明流程跑完了，不说明海报一定好用。这里把确定的版式检查、视觉模型评价和可选注意力预测分别保留下来，再汇总给用户。某个服务不可用就明确标记缺失，其他检查仍可继续；总分只提供参考，不能替代用户的判断。',
  rules:'文字越界、区域重叠等问题可以用明确规则检查，不必每次都问模型。程序拿实际文字区域与画布、其他区域比较，记录问题的位置和严重程度。这样即使模型说画面好看，也能发现真正影响阅读的基础错误。',
  scores:'规则、视觉和注意力分别占 40、35、25 的权重。哪个信号没有结果，就不把它的权重放进分母，并保留缺失标记。注意“不可用”与“真的得了 0 分”是两回事；如果把它们混在一起，就分不清是服务出故障，还是海报本身表现差。',
  comparison:'比较两张海报的分数之前，要先确认使用的信号、评测版本和目标是否一致。如果初版没有视觉结果，修改后服务恢复了，就不能直接拿两个总分宣称效果提升。此时返回 not_comparable，仍然可以逐项观察版式问题和用户反馈。',
  iteration:'用户先说想改什么，模型根据目标选择工具，程序检查后执行，再把结果交回模型。这个循环允许模型根据上一步的成功或失败调整下一步，但单轮最多尝试三个工具，最后统一渲染和评测。这样既能定向修改，也不会无限调用下去。',
  human:'海报生成后先暂停，把结果交给用户。用户可以结束，也可以给出下一轮修改目标。暂停前保存状态，恢复时继续同一个任务，所以已经满意的背景和已有信息可以保留下来，不必每次从头生成。',
  decide:'模型选择动作前，程序会先看这一轮是否已经到达工具次数上限。没到上限才把目标和已有观察结果交给模型，让它选择工具或结束。次数限制必须由程序掌握，否则即使模型一直要求继续，系统也没有可靠的停止边界。',
  execute:'模型提出工具名称和参数后，程序先检查工具是否允许使用、参数是否合法、有没有碰到锁定内容，再执行修改。成功和失败都会记录成观察结果交给模型。模型只负责提出动作，不能绕过这些检查直接改动文件或任意执行代码。',
  locks:'用户要求背景不变或活动事实不变时，程序要在执行修改前后检查这些内容。仅在提示词里提醒模型还不够，因为模型仍可能给出越界的动作。把保留要求变成程序可以核对的条件，才能让局部修改保持可控。',
  round:'一轮里可能连续改几项布局参数，程序等工具动作结束后才统一渲染，再做一次完整评测。这样保留的是这一轮的正式结果，而不是每个临时动作都生成一个版本，也更方便比较修改前后的海报。',
  persistence:'任务信息、暂停状态、图片文件和过程事件各自承担不同作用：知道任务是谁的、从哪里继续、交付什么、为什么得到这个结果。把它们按任务关联起来，刷新页面或排查失败时才不会丢掉上下文。',
  checkpoint:'检查点保存流程暂停的位置和必要状态。用户反馈回来后，程序用同一个任务编号找到检查点，再继续执行。少了这层恢复能力，跨一次请求就可能丢失布局和前面的工具结果，反馈也很难接回原来的任务。',
  artifacts:'每个任务都有自己的文件目录，用来保存海报、评测和相关记录。这样不同任务不会互相覆盖，之后也能根据任务编号找到产物。文件访问仍要经过允许范围检查，不能让一个随意传入的路径读取到项目之外的文件。',
  events:'事件记录能说明哪个节点完成了、调用了什么工具、得到了什么结果，适合展示进度和排查问题。它不是模型私有思考，也不是每一行代码的实时调试记录；当前部分事件是在节点结果返回后再集中发出的。',
  interface:'浏览器收集需求、展示进度和海报，后端负责实际任务。页面提交后先拿到任务编号，再用它接收事件或查询结果。两边各自负责明确的事情，用户才能在等待生成时知道当前发生了什么，并把反馈交回同一个任务。',
  form:'表单先帮用户整理输入并提示常见错误，提交期间避免连续点出重复请求。不过前端按钮不是最终保护，后端仍然要检查输入和任务状态。两层配合，才能既让操作顺手，又避免重复提交把流程推进两次。',
  designhub:'DesignHub 是规划中的团队配套模块：把活动信息、素材、审核和知识维护关联起来。它要解决的是“小团队怎样找到当前能用的正式图”，而不只是再生成一张图片。画布里的模块和实验用于理解未来方案，当前项目还没有实现完整的团队工作台。',
  activities:'假设活动从周五改到周六，旧图虽然审核过，也不能再当成当前正式素材。规划方案让素材绑定活动的具体修订，查询时核对是否仍然一致。这样既能保留旧版本供追溯，也能避免团队误发过期海报。',
  approval:'审核应该针对明确的一版文件，而不是一个之后还能随意变动的名字。规划方案在发布时一起检查审核身份、活动修订和文件摘要，再完成写入。如果检查和发布分开，中途内容被改过，就可能发布一张审核人没有看过的图。',
  'knowledge-data':'知识会更新，建立向量索引也可能失败。规划方案先构建并检查新批次，确认可用后再切换，避免删掉旧数据后新数据又没建好。审核、版本和停用规则一起管理，才能持续知道当前检索到的知识来自哪次发布。',
  assets:'团队找素材时，通常想要的是当前活动已经审核通过的正式版本。规划方案把素材状态、活动修订和文件版本一起核对，过滤掉草稿和过期文件，再返回可用结果。这样“看起来像最终稿”的文件名就不再是判断依据。',
};

const labDescriptions = {
 filter:'改变用途、目标区域或审核开关，看看哪些知识卡会留下来。这里执行仓库里的原筛选函数，使用本地教学卡片，不经过完整数据校验或向量检索。每一步的变量都在画布中，右侧高亮的代码即将执行。',
 similarity:'改两段短文字，看它们怎样被清理、拆成字对，再算出相似度。这里实际执行仓库中的计算函数；语义分数由你输入，没有调用向量模型。单步前进时，会进入内部函数，再带着返回值回到调用处。',
 scores:'把视觉分数设为 0，再试着关闭视觉信号，对比两次结果。原评分函数会真实执行，但视觉分数和注意力顺序都是教学输入，不来自模型服务。你会看到“没有结果”和“结果为零”对分母的影响不同。',
 budget:'假设模型一直想调用工具，保留次数上限时，程序会主动结束；拿掉限制后，它就继续尝试。这里执行的是简化教学函数，最多观察六次，不会真的无限循环，也不会调用模型或业务工具。',
 revision:'假设活动已经改期，看看检查活动修订与不检查时分别会返回哪些素材。这个函数是为解释 DesignHub 规划写的本地模拟，不能当成已实现的团队业务能力。你可以改变修订号，观察旧图何时会被排除。',
};

export function createWorkbench(ctx) {
  const {state,esc,json,children,ancestors,codePanel,transport,sourceCache,kinds}=ctx;
  const data=()=>ctx.data();
  const nodes=()=>ctx.nodes();
  const paragraph=n=>descriptions[n.id]||`${n.summary}${n.mechanism}如果省略这一步，${n.without}`;
  const compact=v=>typeof v==='string'?v:JSON.stringify(v);
  function heading(title,tools='') {return `<div class="work-heading"><h1>${esc(title)}</h1><div class="work-heading-tools">${tools}</div></div>`;}
  function location(id){return `<nav class="canvas-location" aria-label="模块位置">${ancestors(id).map(n=>`<button data-action="node" data-id="${n.id}">${esc(n.id==='system'?'项目整体':n.title)}</button>`).join('<span>›</span>')}</nav>`;}
  function svgLabel(text,x,y,max=14){const chars=Array.from(text);if(/^[\w.<>-]+$/.test(text))max*=2;const lines=[];for(let i=0;i<chars.length;i+=max)lines.push(chars.slice(i,i+max).join(''));return `<text x="${x}" y="${y-(lines.length-1)*10}" text-anchor="middle">${lines.slice(0,3).map((l,i)=>`<tspan x="${x}" dy="${i?21:0}">${esc(l)}</tspan>`).join('')}</text>`;}
  function node(n,x,y,{action='node',selected=false,sub='',width=224,height=78,id=n.id,kind=''}={}){return `<g class="diagram-node ${selected?'current':''} ${n.status==='planned'?'planned':''} ${action==='noop'?'static':''}" ${action==='noop'?'role="img"':`role="button" tabindex="0" data-action="${action}" data-id="${id}"`} ${kind?`data-kind="${kind}"`:''} aria-label="${esc(n.title)}"><rect x="${x}" y="${y}" width="${width}" height="${height}" rx="5"/>${svgLabel(n.id==='system'?'PosterPilot':n.title,x+width/2,y+(sub?31:height/2+5),Math.max(10,Math.floor(width/16)))}${sub?`<text class="node-caption" x="${x+width/2}" y="${y+height-13}" text-anchor="middle">${esc(sub)}</text>`:''}</g>`;}
  const svg=(body,label,height=390)=>`<svg class="diagram" viewBox="0 0 880 ${height}" role="group" aria-label="${esc(label)}"><defs><marker id="arrow-tip" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>${body}</svg>`;
  function moduleMap(n){const kids=children(n.id);if(!kids.length){const count=n.code.length;const cols=count<=4?2:3;const w=cols===2?340:246;const gap=cols===2?58:33;const left=cols===2?71:38;let body='';n.code.forEach((line,i)=>{const x=left+(i%cols)*(w+gap),y=48+Math.floor(i/cols)*112;body+=node({title:line.note},x,y,{action:'line',selected:state.line===i+1,id:i+1,width:w,height:84,sub:'第 '+(i+1)+' 行'});});return svg(body,'点击步骤，对照右侧伪代码',Math.max(330,Math.ceil(count/cols)*112+72));}
    const cols=kids.length<=2?kids.length:3,w=232,gap=32,left=(880-(cols*w+(cols-1)*gap))/2;let lines='',boxes='';kids.forEach((c,i)=>{const x=left+(i%cols)*(w+gap),y=164+Math.floor(i/cols)*130;lines+=`<path class="branch" d="${i<cols?`M440 106 V${y-26} H${x+w/2} V${y}`:`M440 106 V122 H18 V${y-26} H${x+w/2} V${y}`}"/>`;boxes+=node(c,x,y,{width:w,height:86,sub:c.status==='planned'?'规划中 · 点击进入':'点击进入'});});return svg(lines+node(n,322,28,{width:236,selected:true,sub:'当前模块'})+boxes,'模块组成关系',Math.max(340,Math.ceil(kids.length/cols)*130+185));}
  function valueBox(title,value){return `<section class="canvas-value"><span>${esc(title)}</span><pre>${json(value)}</pre></section>`;}
  function lessonIO(n){return `<div class="canvas-data lesson-data">${valueBox('传入',Object.fromEntries(n.inputs.map(x=>[x.name,x.value])))}<span class="data-arrow">→</span>${valueBox('传出',Object.fromEntries(n.outputs.map(x=>[x.name,x.value])))}</div>`;}
  function lessonCode(n){const source=sourceCache.get(n.id);return `<div class="segmented"><button class="${!state.source?'active':''}" data-action="pseudo">初级伪代码</button><button class="${state.source?'active':''}" data-action="source">对照仓库源码</button></div>${state.source?(source?codePanel(source.code.split('\n'),null,{start:source.start,title:n.status==='planned'?'规划文档':'源码对照',meta:source.path+' · '+source.sha256.slice(0,12),note:'这里展示源码原文，不表示完整业务正在执行。'}):'<div class="loading">读取源码…</div>'):codePanel(n.code,state.line,{clickable:true,note:n.code[state.line-1]?.note})}`;}
  function extra(n){return `<div class="explanation-extras">${n.terms.length?`<div class="terms-row">${n.terms.map(t=>`<button class="term" data-action="term" data-id="${esc(t)}">${esc(t)}</button>`).join('')}</div>`:''}${n.quiz?`<details class="quiet-detail"><summary>试着回答一个小问题</summary><section class="quiz"><p>${esc(n.quiz[0])}</p><div class="quiz-options">${n.quiz[1].map((o,i)=>`<button data-action="quiz" data-id="${i}" class="${state.quiz[n.id]===i?'active':''}">${esc(o)}</button>`).join('')}</div>${state.quiz[n.id]!==undefined?`<p class="quiz-feedback">${state.quiz[n.id]===n.quiz[2]?'理解正确。':'再想一想。'}${esc(n.quiz[3])}</p>`:''}</section></details>`:''}<button class="understood" data-action="done">${state.done.has(n.id)?'✓ 已理解（点击取消）':'我已理解这一节'}</button></div>`;}
  function lesson(){const n=nodes().get(state.node),path=data().paths.find(x=>x.id===state.path);const pos=path?.nodes.indexOf(n.id);return `${heading(n.title,`<select id="learning-path" aria-label="学习路径"><option value="">自由探索</option>${data().paths.map(p=>`<option value="${p.id}" ${p.id===state.path?'selected':''}>${esc(p.title)}</option>`).join('')}</select>${path?`<button data-action="path-prev" ${pos<=0?'disabled':''}>上一节</button><button data-action="path-next" ${pos===path.nodes.length-1?'disabled':''}>下一节</button>`:''}`)}<div class="workbench"><section class="visual-work"><div class="study-canvas">${location(n.id)}<div class="canvas-caption"><span>${children(n.id).length?'模块组成 · 点击节点继续深入':'基础步骤 · 点击查看对应代码'}</span><span>${n.status==='planned'?'规划中':'当前实现'}</span></div><div class="canvas-scene">${moduleMap(n)}</div>${lessonIO(n)}<div class="canvas-bottom">${n.parent?`<button data-action="node" data-id="${n.parent}">← 返回上一层</button>`:'<span>从一个模块开始探索</span>'}<span class="canvas-bottom-right">${n.lab?`<button data-action="open-lab" data-id="${n.lab}">修改输入，做个实验 ↗</button>`:''}<button data-action="mode" data-id="runtime">播放完整流程 →</button></span></div></div></section><aside class="explanation-pane"><p class="plain-explanation">${esc(paragraph(n))}</p>${lessonCode(n)}${extra(n)}</aside></div>`;}

  function runMap(tr){const current=tr.steps[state.index];const center=state.index;const indices=Array.from({length:Math.min(5,tr.steps.length)},(_,i)=>Math.min(Math.max(0,center-2),tr.steps.length-5)+i);let body='';indices.forEach((i,j)=>{const s=tr.steps[i],x=24+j*174;if(j<indices.length-1)body+=`<path class="branch flow-link" d="M${x+158} 116 H${x+174}" marker-end="url(#arrow-tip)"/>`;body+=node({title:s.title},x,69,{action:'seek',id:i,kind:'trace',selected:i===center,width:158,height:96,sub:String(i+1).padStart(2,'0')+' / '+tr.steps.length});});body+=`<text x="440" y="226" text-anchor="middle" class="active-caption">${esc(nodes().get(current.node).title)}</text><text x="440" y="257" text-anchor="middle" class="node-caption">${esc(current.actor)}负责${current.wait?' · 等待确认':''}</text>`;return svg(body,'当前步骤与前后步骤',300);}
  function provenance(tr){const fields=[...new Set(tr.steps.slice(0,state.index+1).flatMap(s=>Object.keys(s.state_after)))];if(!fields.includes(state.field))state.field=fields[0];return `<details class="quiet-detail"><summary>追踪数据来源</summary><select id="provenance" aria-label="追踪状态字段">${fields.map(f=>`<option ${f===state.field?'selected':''}>${esc(f)}</option>`).join('')}</select>${tr.steps.slice(0,state.index+1).map((s,i)=>s.changes[state.field]?`<div class="provenance"><span>${esc(s.title)}</span><pre>${json(s.changes[state.field].after)}</pre><button data-action="seek" data-kind="trace" data-id="${i}">回到这一步</button></div>`:'').join('')}</details>`;}
  function runtime(){const tr=state.trace,s=tr?.steps[state.index],n=s?nodes().get(s.node):null;return `${heading('运行回放',`<span class="view-caption">教学示例 · 不调用模型</span>`)}<div class="workbench"><section class="visual-work"><div class="study-canvas">${s?location(s.node):''}<div class="canvas-caption"><span>${s?`${state.index+1} / ${tr.steps.length} · ${esc(s.title)}`:'正在准备…'}</span>${tr?`<select id="step-jump" aria-label="跳到运行步骤">${tr.steps.map((step,i)=>`<option value="${i}" ${i===state.index?'selected':''}>${i+1}. ${esc(step.title)}</option>`).join('')}</select>`:''}</div>${tr?`<div class="canvas-scene">${runMap(tr)}</div><div class="canvas-data">${valueBox('传入',s.input)}<span class="data-arrow">→</span>${valueBox('传出',s.output)}</div><div class="canvas-state">${Object.entries(s.changes).length?Object.entries(s.changes).map(([k,v])=>`<span><b>${esc(k)}</b> ${esc(compact(v.before))} → <strong>${esc(compact(v.after))}</strong></span>`).join(''):'<span>这一步没有修改共享状态</span>'}</div>${transport('trace',tr.steps.length,state.index)}`:'<div class="canvas-placeholder">准备教学示例…</div>'}</div><form id="trace-form" class="canvas-form"><select name="scenario" aria-label="选择场景">${data().scenarios.map(x=>`<option value="${x.id}" ${state.scenario===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select><input name="title" aria-label="活动标题" value="${esc(state.title)}" maxlength="30" required><button ${state.busy?'disabled':''}>重新演示</button></form></section><aside class="explanation-pane">${s?`<p class="plain-explanation">${esc(s.explanation)}</p><div class="current-label">${esc(s.title)}</div>${codePanel(n.code,s.line,{title:'教学伪代码',note:n.code[s.line-1]?.note})}<button class="text-button" data-action="node" data-id="${n.id}">进入这个模块内部 ↗</button>${provenance(tr)}<p class="minor-note">这里按项目控制流演示预设数据，不是完整业务的真实执行记录。真实函数的逐行执行在“动手实验”中。</p>`:''}</aside></div>`;}

  function labForm(l){const v=state.values[l.id]||l.defaults;return `<form id="lab-form" class="canvas-form lab-controls">${l.fields.map(f=>`<label class="${f.type==='checkbox'?'check-control':''}">${f.type==='checkbox'?`<input type="checkbox" name="${f.key}" ${v[f.key]?'checked':''}>${esc(f.label)}`:`<span>${esc(f.label)}</span>${f.type==='select'?`<select name="${f.key}">${f.options.map(o=>`<option ${o===v[f.key]?'selected':''}>${esc(o)}</option>`).join('')}</select>`:`<input name="${f.key}" type="${f.type}" value="${esc(v[f.key])}" ${f.type==='number'?`min="${f.min}" max="${f.max}" step="${f.step}"`:'maxlength="80"'} required>`}`}</label>`).join('')}<button class="primary" ${state.busy?'disabled':''}>${state.busy?'执行中…':'运行这个实验'}</button></form>`;}
  function callMap(l,r,s){const title=s?s.function:{filter:'筛选知识卡',similarity:'计算文本相似度',scores:'汇总可用评分',budget:'检查工具次数',revision:'筛选当前正式素材'}[l.id];const stack=s?.stack||[title];let body='';const shown=stack.slice(-4);const w=Math.min(230,720/shown.length);shown.forEach((fn,i)=>{const x=(880-shown.length*(w+22)+22)/2+i*(w+22);body+=node({title:fn},x,78,{action:'noop',width:w,height:86,selected:i===shown.length-1,sub:i===shown.length-1?(s?.event||'等待运行'):'调用者'});if(i<shown.length-1)body+=`<path class="branch" d="M${x+w} 121 H${x+w+22}" marker-end="url(#arrow-tip)"/>`;});body+=`<text class="active-caption" x="440" y="217" text-anchor="middle">${s?`第 ${s.line} 行 · ${s.event==='return'?'返回结果':s.event==='call'?'进入函数':'即将执行'}`:'修改下方输入，然后运行'}</text>`;return svg(body,'函数调用关系',265);}
  function lab(){const l=data().labs.find(x=>x.id===state.lab),r=state.result,s=r?.steps[state.labIndex];const previous=r?.steps[state.labIndex-1];const vals=s?.event==='return'?s.returned:s?.locals;return `${heading('动手实验',`<select id="lab-choice" aria-label="选择实验">${data().labs.map(x=>`<option value="${x.id}" ${x.id===l.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select>`)}<div class="workbench"><section class="visual-work"><div class="study-canvas">${location(l.node)}<div class="canvas-caption"><span>${kinds[l.kind]}</span>${r?`<select id="lab-jump" aria-label="跳到执行事件">${r.steps.map((e,i)=>`<option value="${i}" ${i===state.labIndex?'selected':''}>${i+1}. ${esc(e.function)} · ${e.event} : ${e.line}</option>`).join('')}</select>`:''}</div><div class="canvas-scene">${callMap(l,r,s)}</div><div class="canvas-data lab-data">${valueBox('实验输入',r?.input||state.values[l.id]||l.defaults)}<span class="data-arrow">→</span><section class="canvas-value"><span>${s?.event==='return'?'函数返回值':'当前变量'}</span>${s?`<div class="variable-list">${vals&&typeof vals==='object'?Object.entries(vals).map(([key,value])=>`<div class="variable ${JSON.stringify(previous?.locals?.[key])!==JSON.stringify(value)?'changed':''}"><b>${esc(key)}</b><pre>${json(value)}</pre></div>`).join(''):`<pre>${json(vals)}</pre>`}</div>`:'<p>运行后，变量会随着代码逐步变化。</p>'}</section></div>${r?transport('lab',r.steps.length,state.labIndex):'<div class="canvas-bottom"><span>输入和执行都在本机，不产生模型费用。</span></div>'}</div>${labForm(l)}</section><aside class="explanation-pane"><p class="plain-explanation">${esc(labDescriptions[l.id])}</p>${r?`${codePanel(r.source.code.split('\n'),s.line,{start:r.source.start,title:s.function+' · '+s.event,meta:r.source.path,note:s.explanation})}<div class="function-controls"><button data-action="over">跳过函数内部</button><button data-action="out">运行到返回</button></div><details class="quiet-detail lab-summary"><summary>查看本次最终输出${state.previous?'与上次比较':''}</summary><pre>${json(r.output)}</pre>${state.previous?`<p>上次输入</p><pre>${json(state.previous.input)}</pre><p>上次输出</p><pre>${json(state.previous.output)}</pre>`:''}</details>`:`<p class="minor-note">运行后，这里会显示实际执行的代码。你可以一步步进入函数，看它接收什么、改变什么、返回什么。</p>`}<button class="text-button" data-action="node" data-id="${l.node}">回到这个模块的讲解 ↗</button></aside></div>`;}
  return {lesson,runtime,lab};
}
